### ISSUE TITLE
OpenSPA is not open source anymore

### ISSUE THREAD

**Issue by persianpros** [oe-alliance/bootmenu#182]
Regarding https://github.com/OpenVisionE2/bootmenu/commit/70b60ef147f0056e7c5a7d15efda916bfe8f608e

It is clear that this team is not using OE-A anymore although OE-A shows OpenSPA as a member but if you check https://github.com/oe-alliance/oe-alliance-core/blob/5.3/meta-oe/conf/distro/openspa.conf#L10 and their download server you'll see new images are 8.x with no sources available to check.

Their e2 repo is https://github.com/OpenSPA/dvbapp2 and since August 2022 it didn't receive any updates, if you check a new image and its e2 like https://openspa.webhop.info/feeds/8.1/h9/zgemmah9t/enigma2_8.1+git26896+0b2cc61-r0_zgemmah9t.ipk you'll see the git revision is not availabe to check so they use a private git for their e2 which makes an e2 image not open source.

Just wanted to let you know.

**Comment by persianpros** [comment]
There are more closed source images in this repo and after https://github.com/oe-alliance/bootmenu/issues/85 and the cleanups you made it's weird to see them like:

PKT images which are fully closed. (Example: https://github.com/oe-alliance/bootmenu/blob/master/sf8008/images#L12)

AREADELTASAT which since October 2021 it didn't receive any e2 updates so where the new images are coming from? Check https://github.com/AREADELTASAT?tab=repositories you'll get what I mean. (Example: https://github.com/oe-alliance/bootmenu/blob/master/sf8008/images#L26)

**Comment by Huevos** [comment]
Yes, I agree that any image that is not open source should be removed.

And by the way what is the current status of OpenVision (enigma and core)?

**Comment by persianpros** [comment]
OV's e2 is always open and I mean fully open not like ATV which I had to do https://github.com/OpenVisionE2/enigma2-openvision/commit/9c4f9e5e28be97a2c73b63cb829858a297f9e188 (sadly) regarding it because they're using a private patch for supporting dreamone and dreamtwo. We don't use private patches to change e2 this means e2 is not fully open.

You can compile OV with OE-A with https://github.com/OpenVisionE2/ov-expansion but we don't provide our OE sources (at least not for now) but if OE-A members give me write access I'll bring the goods from our OE to OE-A into a development branch so later could be merged into 5.3

Although we're not part of OE-A but I think merging https://github.com/OpenVisionE2/ov-expansion into OE-A is a good idea to let others be able to compile OV with OE-A and you could write it's a partnership just for cooperation as we would like to contribute to OE-A just like I always try to contribute to ViX and others.

Having more friends come handy all the time :+1:

**Comment by Ev0-BH** [comment]
> OV's e2 is always open and I mean fully open not like ATV which I had to do [OpenVisionE2/enigma2-openvision@9c4f9e5](https://github.com/OpenVisionE2/enigma2-openvision/commit/9c4f9e5e28be97a2c73b63cb829858a297f9e188) (sadly) 
> Having more friends come handy all the time 👍

Not sure renaming another distro is the best way to make friends though

**Comment by persianpros** [comment]
We don't have any problem with ATV, in fact we keep our sources in sync always.

OV and ATV are much similar to each other if you compare them with other images and it's just a name change, if they publish the sources later I will revert the name changes.

**Comment by Ev0-BH** [comment]
I'm confused.

How is what ATV are doing (for whatever reason they have), any different from you not providing your OE sources ?

**Comment by persianpros** [comment]
An open image is an image with fully open enigma2 as you can build it with other OEs like official OE or OE-A but keeping things out of e2 and apply them as private patches is something that makes e2 different and closed somehow.

**Comment by Ev0-BH** [comment]
Well either way, I personally think it is wrong for you to rename another distro just because you are not happy about the way they do things.

I do not think it is the way forward, but it's just my view.

**Comment by persianpros** [comment]
And for you to remember: https://github.com/oe-alliance/bootmenu/commit/692001f6f804fbc05f2c8e81ba0e6f320988aeda

We contribute to all projects that we can and our e2 is fully open.

**Comment by AbuBaniaz** [comment]
We are currently discussing what rules to apply for all teams that want to be on the boot menu that OE-A has.

All E2 teams do this in their free time. We will achieve more if work together and amicably despite differences.

What you name other teams on your image is up to you. But we are all in charge of our own actions, not of others. I personally would suggest that you undo the name change. That action does not reflect your best side.

Most of us look forward to positive contribution from others. 

I am going to close this issue now.

**Comment by persianpros** [comment]
@AbuBaniaz 

It's not just about this repo, OpenSPA is using everyone's work inside their e2 and their e2 repo isn't open. If you grab a recent image you can just check for "International.py" for example which is a work by @IanSav to understand what I'm saying.

Is OE-A philosophy about advertising an image with closed e2? OpenSPA is a member of OE-A.

There are more closed-souce images out there but none are a member of OE-A.
